import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar/Navbar";
import LoginModal from "./components/modals/LoginModal";
import SingupModal from "./components/modals/SingupModal";

const inter = Inter({ subsets: ["latin"] });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const content = (
      <p>Yo yo</p>
  )

  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>

          <div className="pt-32">
            {children}
          </div>

          <LoginModal  />
          <SingupModal />
        </body>
    </html>
  );
}
